services:
  domain.storage.composite:
    class: Vainyl\Domain\Storage\CompositeDomainStorage
    arguments: ['@storage.prototype']
  domain.storage: '@domain.storage.composite'
  domain.operation.factory.composite:
    class: Vainyl\Domain\Operation\Factory\CompositeDomainOperationFactory
    arguments: ['@storage.prototype']
  domain.operation.factory: '@domain.operation.factory.composite'