services:
  domain.storage.composite:
    class: Vainyl\Domain\Storage\CompositeDomainStorage
    arguments: ['@map.prototype']
  domain.storage: '@domain.storage.composite'
  domain.scenario.storage: '@domain.storage.composite'
  domain.operation.factory.composite:
    class: Vainyl\Domain\Operation\Factory\CompositeDomainOperationFactory
    arguments: ['@map.prototype']
  domain.operation.factory: '@domain.operation.factory.composite'
  domain.operation.factory.event:
    class: Vainyl\Domain\Operation\Decorator\EventDomainOperationFactoryDecorator
    decorates: domain.operation.factory
    decoration_priority: 1000
    arguments: ['@domain.operation.factory.event.inner', '@collection.factory.sequence', '@event.dispatcher.collection']
  domain.operation.factory.timestamp:
    class: Vainyl\Domain\Operation\Decorator\TimestampDomainOperationFactoryDecorator
    decorates: domain.operation.factory
    decoration_priority: 100
    arguments: ['@domain.operation.factory.timestamp.inner', '@collection.factory.sequence', '@time.provider']
  domain.operation.factory.scenario:
    class: Vainyl\Domain\Operation\Decorator\ScenarioDomainOperationFactoryDecorator
    decorates: domain.operation.factory
    decoration_priority: 200
    arguments: ['@domain.operation.factory.scenario.inner', '@collection.factory.sequence', '@domain.scenario.storage']
  domain.hydrator.composite:
    class: Vainyl\Domain\Hydrator\CompositeDomainHydrator
    arguments: ['@map.prototype']
  domain.hydrator: '@domain.hydrator.composite'